conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("accounts.urls")),
    path("", include(("vacancies.public.urls", "public"), namespace="public")),
    path("", include(("vacancies.company.urls", "company"), namespace="company")),
    path("", include(("vacancies.resume.urls", "resume"), namespace="resume")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vacancies/company/urls.py
from django.urls import path

from .views import (
    MyCompanyCreate,
    MyCompanyEdit,
    MyCompanyLetsstart,
    MyCompanyVacancyCreate,
    MyCompanyVacancyEdit,
    MyCompanyVacancyList,
)

urlpatterns = [
    path("mycompany/", MyCompanyEdit.as_view(), name="my_company"),
    path("mycompany/letsstart/", MyCompanyLetsstart.as_view(), name="my_company_letsstart"),
    path("mycompany/create/", MyCompanyCreate.as_view(), name="my_company_create"),
    path("mycompany/vacancies/", MyCompanyVacancyList.as_view(), name="my_company_vacancies"),
    path("mycompany/vacancies/create/", MyCompanyVacancyCreate.as_view(), name="my_company_vacancy_create"),
    path("mycompany/vacancies/<int:pk>/", MyCompanyVacancyEdit.as_view(), name="my_company_vacancy_edit"),
]

vacancies/resume/urls.py
from django.urls import path

from .views import MyResumeCreate, MyResumeEdit, MyResumeLetsstart

urlpatterns = [
    path("myresume/", MyResumeEdit.as_view(), name="my_resume"),
    path("myresume/letsstart/", MyResumeLetsstart.as_view(), name="my_resume_letsstart"),
    path("myresume/create/", MyResumeCreate.as_view(), name="my_resume_create"),
]

vacancies/models.py
#####################################################################
#       Existed users (login / password)                            #
#        - admin / admin                                            #
#        - user1 / 123                                              #
#        - user2 / 123                                              #
#        - ...                                                      #
#        - user8 / 123                                              #
#####################################################################

from conf.settings import MEDIA_COMPANY_IMAGE_DIR
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField


class Company(models.Model):
    name = models.CharField(max_length=256)
    location = models.CharField(max_length=128)
    description = models.TextField()
    employee_count = models.IntegerField()
    owner = models.OneToOneField(User, on_delete=models.CASCADE, related_name="company", null=True)
    logo = models.ImageField(upload_to=MEDIA_COMPANY_IMAGE_DIR)

    def delete(self, *args, **kwargs):
        self.picture.storage.delete(self.picture.path)
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.name


class Specialty(models.Model):
    code = models.CharField(max_length=32)
    title = models.CharField(max_length=128)
    picture = models.URLField(default="https://place-hold.it/100x60")

    def __str__(self):
        return self.title


class Vacancy(models.Model):
    title = models.CharField(max_length=256)
    specialty = models.ForeignKey(Specialty, on_delete=models.CASCADE, related_name="vacancies")
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="vacancies")
    skills = models.CharField(max_length=512)
    description = models.TextField()
    salary_min = models.IntegerField()
    salary_max = models.IntegerField()
    published_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("vacancies", kwargs={"pk": self.pk})

    def clean(self):
        super().clean()
        if int(self.salary_min) >= int(self.salary_max):
            raise ValidationError({"salary_min": ValidationError("Значение должно быть меньше максимального")})
        return


class Application(models.Model):
    written_username = models.CharField(max_length=256)
    written_phone = PhoneNumberField()
    written_cover_letter = models.TextField()
    vacancy = models.ForeignKey(Vacancy, on_delete=models.CASCADE, related_name="applications")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="applications")

    def __str__(self):
        return f"{self.user.username}:{self.vacancy.title}"


class Resume(models.Model):
    class Grade(models.TextChoices):
        TRAINEE = "TRAINEE", _("Стажер")
        JUNIOR = "JUNIOR", _("Джуниор")
        MIDDLE = "MIDDLE", _("Миддл")
        SENIOR = "SENIOR", _("Синьор")
        LEAD = "LEAD", _("Лид")

    class Status(models.TextChoices):
        CLOSE = "CLOSE", _("Не ищу работу")
        PASSIVE = "PASSIVE", _("Рассматриваю предложения")
        ACTIVE = "ACTIVE", _("Ищу работу")

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="resume")
    name = models.CharField(max_length=128)
    surname = models.CharField(max_length=128)
    status = models.CharField(max_length=32, choices=Status.choices, default=Status.CLOSE)
    salary = models.IntegerField()
    specialty = models.ForeignKey(Specialty, on_delete=models.SET_NULL, null=True)
    grade = models.CharField(max_length=32, choices=Grade.choices, default=Grade.TRAINEE)
    education = models.TextField()
    experience = models.TextField()
    portfolio = models.URLField(blank=True)

    def __str__(self):
        return f"Resume: {self.user.username}-{self.specialty.code}"

templates/base.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <title>Джуманджи</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <header class="container mt-3">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand mr-4" href="{% url 'public:main' %}">Джуманджи</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
                <ul class="navbar-nav col-10">
                    <li class="nav-item">
                        {% url 'public:vacancies' as vacancies_url %}
                        <a class="nav-link {% if request.path == vacancies_url %}active{% endif %}"
                            href="{% url 'public:vacancies' %}">Вакансии</a>
                    </li>

                </ul>
                <ul class="navbar-nav col-2 justify-content-end">
                    <li class="nav-item active">
                        {% if user.is_authenticated %}

                        <div class="btn-group">
                            <button type="button" class="btn dropdown-toggle font-weight-bold" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                                {{ user.first_name}} {{ user.last_name}}
                            </button>
                            <div class="dropdown-menu dropdown-menu-right mt-3">
                                <a href="#" class="dropdown-item py-2">Профиль</a>
                                <a href="{% url 'resume:my_resume' %}" class="dropdown-item py-2">Резюме</a>
                                <a href="{% url 'company:my_company' %}" class="dropdown-item py-2">Компания</a>
                                <a href="{% url 'logout' %}" class="dropdown-item py-2">Выйти</a>
                            </div>
                        </div>


                        {% else %}

                        <a href="{% url 'login' %}" class="nav-link font-weight-bold">Вход</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <main class="container mt-3">

        {% block main %} {% endblock %}

    </main>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>