conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("accounts.urls")),
    path("", include(("vacancies.public.urls", "public"), namespace="public")),
    path("", include(("vacancies.company.urls", "company"), namespace="company")),
    path("", include(("vacancies.resume.urls", "resume"), namespace="resume")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vacancies/company/urls.py
from django.urls import path

from .views import (
    MyCompanyCreate,
    MyCompanyEdit,
    MyCompanyLetsstart,
    MyCompanyVacancyCreate,
    MyCompanyVacancyEdit,
    MyCompanyVacancyList,
)

urlpatterns = [
    path("mycompany/", MyCompanyEdit.as_view(), name="my_company"),
    path("mycompany/letsstart/", MyCompanyLetsstart.as_view(), name="my_company_letsstart"),
    path("mycompany/create/", MyCompanyCreate.as_view(), name="my_company_create"),
    path("mycompany/vacancies/", MyCompanyVacancyList.as_view(), name="my_company_vacancies"),
    path("mycompany/vacancies/create/", MyCompanyVacancyCreate.as_view(), name="my_company_vacancy_create"),
    path("mycompany/vacancies/<int:pk>/", MyCompanyVacancyEdit.as_view(), name="my_company_vacancy_edit"),
]

vacancies/resume/urls.py
from django.urls import path

from .views import MyResumeCreate, MyResumeEdit, MyResumeLetsstart

urlpatterns = [
    path("myresume/", MyResumeEdit.as_view(), name="my_resume"),
    path("myresume/letsstart/", MyResumeLetsstart.as_view(), name="my_resume_letsstart"),
    path("myresume/create/", MyResumeCreate.as_view(), name="my_resume_create"),
]

vacancies/models.py
#####################################################################
#       Existed users (login / password)                            #
#        - admin / admin                                            #
#        - user1 / 123                                              #
#        - user2 / 123                                              #
#        - ...                                                      #
#        - user8 / 123                                              #
#####################################################################

from conf.settings import MEDIA_COMPANY_IMAGE_DIR
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField


class Company(models.Model):
    name = models.CharField(max_length=256)
    location = models.CharField(max_length=128)
    description = models.TextField()
    employee_count = models.IntegerField()
    owner = models.OneToOneField(User, on_delete=models.CASCADE, related_name="company", null=True)
    logo = models.ImageField(upload_to=MEDIA_COMPANY_IMAGE_DIR)

    def delete(self, *args, **kwargs):
        self.picture.storage.delete(self.picture.path)
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.name


class Specialty(models.Model):
    code = models.CharField(max_length=32)
    title = models.CharField(max_length=128)
    picture = models.URLField(default="https://place-hold.it/100x60")

    def __str__(self):
        return self.title


class Vacancy(models.Model):
    title = models.CharField(max_length=256)
    specialty = models.ForeignKey(Specialty, on_delete=models.CASCADE, related_name="vacancies")
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="vacancies")
    skills = models.CharField(max_length=512)
    description = models.TextField()
    salary_min = models.IntegerField()
    salary_max = models.IntegerField()
    published_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("vacancies", kwargs={"pk": self.pk})

    def clean(self):
        super().clean()
        if int(self.salary_min) >= int(self.salary_max):
            raise ValidationError({"salary_min": ValidationError("Значение должно быть меньше максимального")})
        return


class Application(models.Model):
    written_username = models.CharField(max_length=256)
    written_phone = PhoneNumberField()
    written_cover_letter = models.TextField()
    vacancy = models.ForeignKey(Vacancy, on_delete=models.CASCADE, related_name="applications")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="applications")

    def __str__(self):
        return f"{self.user.username}:{self.vacancy.title}"


class Resume(models.Model):
    class Grade(models.TextChoices):
        TRAINEE = "TRAINEE", _("Стажер")
        JUNIOR = "JUNIOR", _("Джуниор")
        MIDDLE = "MIDDLE", _("Миддл")
        SENIOR = "SENIOR", _("Синьор")
        LEAD = "LEAD", _("Лид")

    class Status(models.TextChoices):
        CLOSE = "CLOSE", _("Не ищу работу")
        PASSIVE = "PASSIVE", _("Рассматриваю предложения")
        ACTIVE = "ACTIVE", _("Ищу работу")

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="resume")
    name = models.CharField(max_length=128)
    surname = models.CharField(max_length=128)
    status = models.CharField(max_length=32, choices=Status.choices, default=Status.CLOSE)
    salary = models.IntegerField()
    specialty = models.ForeignKey(Specialty, on_delete=models.SET_NULL, null=True)
    grade = models.CharField(max_length=32, choices=Grade.choices, default=Grade.TRAINEE)
    education = models.TextField()
    experience = models.TextField()
    portfolio = models.URLField(blank=True)

    def __str__(self):
        return f"Resume: {self.user.username}-{self.specialty.code}"

vacancies/company/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Column, Layout, Row, Submit
from django import forms
from vacancies.models import Company, Vacancy


class VacancyForm(forms.ModelForm):
    class Meta:
        model = Vacancy
        fields = (
            "title",
            "specialty",
            "skills",
            "description",
            "salary_min",
            "salary_max",
        )
        labels = {
            "title": "Название вакансии",
            "specialty": " Специализация",
            "skills": "Навыки",
            "description": "Описание вакансии",
            "salary_min": "Зарплата от",
            "salary_max": "Зарплата до",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.label_class = "mb-2 text-dark"
        self.helper.add_input(Submit("submit", "Сохранить", css_class="btn btn-primary btn-block"))
        self.helper.layout = Layout(
            Row(Column("title")),
            Row(
                Column("specialty"),
                Column("skills"),
            ),
            Row(Column("description")),
            Row(
                Column("salary_min"),
                Column("salary_max"),
            ),
        )


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = (
            "name",
            "location",
            "description",
            "employee_count",
            "logo",
        )
        labels = {
            "name": "Название компании",
            "location": "Локация",
            "description": "Информация о компании",
            "employee_count": "Количество человек в компании",
            "logo": "Логотип",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.label_class = "mb-2 text-dark"
        self.helper.add_input(Submit("submit", "Сохранить", css_class="btn btn-primary btn-block"))
        self.helper.layout = Layout(
            Row(Column("name")),
            Row(
                Column("location"),
                Column("employee_count"),
            ),
            Row(Column("logo")),
            Row(Column("description")),
        )

vacancies/resume/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Column, Layout, Row, Submit
from django import forms
from vacancies.models import Resume


class ResumeForm(forms.ModelForm):
    class Meta:
        model = Resume
        fields = (
            "name",
            "surname",
            "status",
            "salary",
            "specialty",
            "grade",
            "education",
            "experience",
            "portfolio",
        )
        labels = {
            "name": "Имя",
            "surname": "Фамилия",
            "status": "Готовность к работе",
            "salary": "Желаемый оклад",
            "specialty": "Специализация",
            "grade": "Уровень",
            "education": "Образование",
            "experience": "Опыт работы",
            "portfolio": "Портфолио",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.label_class = "mb-2 text-dark"
        self.helper.add_input(Submit("submit", "Сохранить", css_class="btn btn-primary btn-block"))
        self.helper.layout = Layout(
            Row(
                Column("name"),
                Column("surname"),
            ),
            Row(
                Column("salary"),
                Column("status"),
            ),
            Row(
                Column("specialty"),
                Column("grade"),
            ),
            Row(Column("education")),
            Row(Column("experience")),
            Row(Column("portfolio")),
        )

vacancies/company/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Count
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic import ListView, View
from django.views.generic.base import TemplateView
from vacancies.models import Company, Vacancy

from .forms import CompanyForm, VacancyForm

#####################################################################
#                       MyCompany Lets Start                        #
#####################################################################


class MyCompanyLetsstart(LoginRequiredMixin, TemplateView):
    template_name = "vacancies/company/my_company_letsstart.html"

    def get(self, request, *args, **kwargs):
        if Company.objects.filter(owner__pk=request.user.pk).first():
            return redirect(reverse("company:my_company"))
        return super().get(request, *args, **kwargs)


#####################################################################
#                              MyCompany                            #
#####################################################################


class MyCompanyCreate(LoginRequiredMixin, View):
    def get(self, request):
        company = Company.objects.filter(owner__pk=request.user.pk).first()
        if company:
            return redirect(reverse("company:my_company"))
        form = CompanyForm()
        return render(request, "vacancies/company/my_company_edit.html", {"form": form})

    def post(self, request):
        company = Company.objects.filter(owner__pk=request.user.pk).first()
        form = CompanyForm(request.POST, request.FILES, instance=company)
        if form.is_valid():
            company = form.save(commit=False)
            company.owner = get_object_or_404(User, pk=request.user.pk)
            company.save()
            messages.add_message(request, messages.INFO, "Данные сохранены")
            return redirect(reverse("company:my_company"))
        else:
            return render(request, "vacancies/company/my_company_edit.html", {"form": form})


class MyCompanyEdit(MyCompanyCreate):
    def get(self, request):
        company = Company.objects.filter(owner__pk=request.user.pk).first()
        if not company:
            return redirect(reverse("company:my_company_letsstart"))
        else:
            form = CompanyForm(instance=company)
            return render(request, "vacancies/company/my_company_edit.html", {"form": form})


#####################################################################
#                        MyCompany Vacancies                        #
#####################################################################


class MyCompanyVacancyList(LoginRequiredMixin, ListView):
    template_name = "vacancies/company/my_company_vacancies.html"

    def get_queryset(self):
        return Vacancy.objects.filter(
            company__owner__id=self.request.user.pk,
        ).annotate(application_count=Count("applications"))


class MyCompanyVacancyCreate(LoginRequiredMixin, View):
    def get(self, request, vacancy=None):
        form = VacancyForm(instance=vacancy)
        return render(
            request,
            "vacancies/company/my_company_vacancy_edit.html",
            {
                "form": form,
                "vacancy": vacancy,
            },
        )

    def post(self, request, **kwargs):
        vacancy_pk = self.kwargs.get("pk", None)
        vacancy = Vacancy.objects.filter(
            pk=vacancy_pk,
            company__owner__id=request.user.pk,
        ).first()
        form = VacancyForm(data=request.POST, instance=vacancy)
        if form.is_valid():
            vacancy = form.save(commit=False)
            vacancy.company = Company.objects.filter(owner__id=request.user.pk).first()
            vacancy.save()
            messages.add_message(request, messages.INFO, "Данные сохранены")
            return redirect(reverse("company:my_company_vacancy_edit", kwargs={"pk": vacancy.pk}))

        else:
            return render(request, "vacancies/company/my_company_vacancy_edit.html", {"form": form})


class MyCompanyVacancyEdit(MyCompanyVacancyCreate):
    def get(self, request, pk):
        vacancy = (
            Vacancy.objects.filter(pk=pk, company__owner__id=request.user.pk)
            .prefetch_related("applications")
            .annotate(application_count=Count("applications"))
            .first()
        )
        if not vacancy:
            raise Http404
        return super().get(request, vacancy)

vacancies/resume/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic import View
from django.views.generic.base import TemplateView
from vacancies.models import Resume

from .forms import ResumeForm

#####################################################################
#                        MyResume Lets Start                        #
#####################################################################


class MyResumeLetsstart(LoginRequiredMixin, TemplateView):
    template_name = "vacancies/resume/my_resume_letsstart.html"

    def get(self, request, *args, **kwargs):
        if Resume.objects.filter(user__pk=request.user.pk).first():
            return redirect(reverse("resume:my_resume"))
        return super().get(request, *args, **kwargs)


#####################################################################
#                              MyResume                             #
#####################################################################


class MyResumeCreate(LoginRequiredMixin, View):
    def get(self, request):
        resume = Resume.objects.filter(user__pk=request.user.pk).first()
        if resume:
            return redirect(reverse("resume:my_resume"))
        form = ResumeForm()
        return render(request, "vacancies/resume/my_resume_edit.html", {"form": form})

    def post(self, request):
        resume = Resume.objects.filter(user__pk=request.user.pk).first()
        form = ResumeForm(data=request.POST, instance=resume)
        if form.is_valid():
            resume = form.save(commit=False)
            resume.user = get_object_or_404(User, pk=request.user.pk)
            resume.save()
            messages.add_message(request, messages.INFO, "Данные сохранены")
            return redirect(reverse("resume:my_resume"))
        else:
            return render(request, "vacancies/resume/my_resume_edit.html", {"form": form})


class MyResumeEdit(MyResumeCreate):
    def get(self, request):
        resume = Resume.objects.filter(user__pk=request.user.pk).first()
        if not resume:
            return redirect(reverse("resume:my_resume_letsstart"))
        else:
            form = ResumeForm(instance=resume)
            return render(request, "vacancies/resume/my_resume_edit.html", {"form": form})

templates/vacancies/helpers/application_card.html
{% load static %}
{% load helpers %}

<div class="card mt-3">
    <div class="card-body px-4">
        <p class="mb-1 font-weight-bold">{{ application.written_username }}</p>
        <p class="mb-2"><a href="tel:+79002842324" class="text-dark">{{ application.written_phone }}</a>
        </p>
        <p class="mb-1">{{ application.written_cover_letter }}</p>
    </div>
</div>

templates/vacancies/helpers/company_card.html
{% load static %}
{% load helpers %}

<div class="col-6 col-md-6 col-lg-3">
    <div class="card pt-4 text-center mb-4">
        {% if company.logo %}
        <a href="{% url 'public:company' company.pk %}" style="max-width: 150px;" class="mx-auto d-block">
            <img class="mx-auto d-block mw-100" src="{{ company.logo.url }}" alt="">
        </a>
        {% else %}
        <img class="mx-auto d-block" src="https://place-hold.it/150x80" width="150" height="80" alt="">
        {% endif %}
        <div class="card-body">
            <p class="card-text">
                <a href="{% url 'public:company' company.pk %}">
                    {{company.vacancies_count|ru_pluralize:'вакансия,вакансии,вакансий'}}
                </a>
            </p>
        </div>
    </div>
</div>

templates/vacancies/helpers/company_logo.html
{% if company.logo %}
<a href="{% url 'public:company' company.pk %}" style="max-width: 150px;" class="mx-auto d-block">
    <img class="mx-auto d-block mw-100" src="{{ company.logo.url }}" alt="">
</a>
{% else %}
<img class="mx-auto d-block" src="https://place-hold.it/150x80" width="150" height="80" alt="">
{% endif %}

templates/vacancies/helpers/search_panel.html
<div class="row">
    <div class="col-12 col-md-8 col-lg-6 offset-lg-3 offset-md-2">
        <form class="form-inline sm-form mr-auto mb-4" enctype="multipart/form-data"
            action="{% url 'public:search_results' %}" method="GET">
            <div class="form-group col-8 col-md-10 pl-0">
                <input name="q" type="text" class="form-control w-100" placeholder="Найти работу или стажировку"
                    value="{{ search_string }}" autofocus="autofocus">
            </div>
            <div class="form-group col-4 col-md-2 pl-0">
                <button class="btn btn-primary w-100" type="submit">Найти</button>
            </div>
        </form>
        <p>Например:
            <a href="{% url 'public:search_results' %}?q=Python"
                class="text-dark border-bottom border-dark m-1 text-decoration-none">Python</a>
            <a href="{% url 'public:search_results' %}?q=Flask"
                class="text-dark border-bottom border-dark m-1 text-decoration-none">Flask</a>
            <a href="{% url 'public:search_results' %}?q=Django"
                class="text-dark border-bottom border-dark m-1 text-decoration-none">Django</a>
            <a href="{% url 'public:search_results' %}?q=Парсинг"
                class="text-dark border-bottom border-dark m-1 text-decoration-none">Парсинг</a>
            <a href="{% url 'public:search_results' %}?q=ML"
                class="text-dark border-bottom border-dark m-1 text-decoration-none">ML</a>
        </p>
    </div>
</div>

templates/vacancies/helpers/specialty_card.html
{% load static %}
{% load helpers %}

<div class="col-6 col-md-6 col-lg-3">
    <div class="card pt-4 text-center mb-4">
        <a href="{% url 'public:vacancies' specialty.code %}">
            <img class="mx-auto d-block" src="{% static specialty.picture %}" width="80" height="80" alt="">
        </a>
        <div class="card-body">
            <p class="card-text mb-2">{{ specialty.title }}</p>
            <p class="card-text">
                <a href="{% url 'public:vacancies' specialty.code %}">
                    {{specialty.vacancies_count|ru_pluralize:'вакансия,вакансии,вакансий' }}
                </a>
            </p>
        </div>
    </div>
</div>

templates/vacancies/helpers/vacancy_company_card.html
{% load static %}
{% load helpers %}

<div class="card mt-3">
    <div class="card-body px-4">
        <div class="row align-items-center">
            <div class="col-6 col-lg-8">
                <h3>
                    <a href="{% url 'public:vacancy' vacancy.id %}" class="mb-1 text-primary">
                        {{ vacancy.title }}
                    </a>
                </h3>
                <p class="mb-1">
                    <span class="mr-4">От {{ vacancy.salary_min }} до {{ vacancy.salary_max }} руб.</span>
                    <span class="strong">{{ vacancy.application_count|ru_pluralize:'отклик,отклика,откликов' }}</span>
                </p>
            </div>
            <div class="col-6 col-lg-4 text-right">
                <a href="{% url 'company:my_company_vacancy_edit' vacancy.id %}"
                    class="btn btn-outline-primary">Изменить</a>
            </div>
        </div>
    </div>
</div>

templates/vacancies/helpers/vacancy_public_card.html
{% load static %}

<div class="card mb-4">
    <div class="card-body px-4">
        <div class="row">
            <div class="col-12 col-md-8 col-lg-9">
                <h2 class="h2 pb-2">
                    <a href="{% url 'public:vacancy' vacancy.id %}">
                        {{ vacancy.title }}
                    </a>
                </h2>
                <p class="mb-2">{{ vacancy.skills }}</p>
                <p>От {{ vacancy.salary_min }} до {{ vacancy.salary_max }}руб.</p>
                <p class="text-muted pt-1">{{ vacancy.published_at }}</p>
            </div>
            <div class="col-12 col-md-4 col-lg-3 d-flex align-items-end">
                {% include "vacancies/helpers/company_logo.html" with company=vacancy.company %}
            </div>
        </div>
    </div>
</div>